language: java
jdk:
  - oraclejdk7

notifications:
  email:
    - fkorotkov@twitter.com

install: ./scripts/setup-ci-environment.sh

env:
  global:
    - OSS_PANTS_HOME=./.cache/intellij/pants
  matrix:
    - IJ_VERSION="14.1" IJ_BUILD_NUMBER="141.177" IJ_ULTIMATE=true
    - IJ_VERSION="14.1" IJ_BUILD_NUMBER="141.177"

script:
  - ./scripts/run-tests-ci.sh --test-junit-jvm-options="-Dpants.compiler.enabled=${USE_PANTS_TO_COMPILE:-true}"
  - ./scripts/run-custom-integration.sh
      -r $OSS_PANTS_HOME
      -t examples/src/scala/org/pantsbuild/example/hello,examples/src/java/org/pantsbuild/example/hello
